# Generated by Django 5.2.1 on 2025-06-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['-category'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
